# Generated by Django 5.0.1 on 2024-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("imge", models.FileField(blank=True, null=True, upload_to="images/")),
            ],
        ),
    ]
