# Generated by Django 5.0.1 on 2024-02-03 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="likes",
                through="tweets.TweetLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
