# Generated by Django 5.0.1 on 2024-02-01 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="text",
            new_name="content",
        ),
    ]
